name: Atualizar Vagas Automaticamente

on:
  schedule:
    - cron: '0 8 * * *' # Executa automaticamente todos os dias às 08:00 UTC
  workflow_dispatch: # Permite disparar a execução manualmente a qualquer momento pelo painel do GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install requests supabase beautifulsoup4

      - name: Executar Raspador
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        run: |
          python raspador.py
